In [1]:
import numpy as np 
import matplotlib.pyplot as plt


In [4]:
array1 = np.array([1,2,3,4,5])
array2 = np.random.rand(3,3)
array3 = np.zeros((4,4))
print(array1,array2,array3)

[1 2 3 4 5] [[0.75720965 0.56693299 0.7296195 ]
 [0.41760626 0.91635454 0.09857801]
 [0.17983686 0.44214889 0.64038108]] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
np.save("array1.npy",array1)
np.save("array2.npy",array2)
np.save("array3.npy",array3)

In [7]:
loaded_array1 = np.load("array1.npy")
print(loaded_array1)

[1 2 3 4 5]


In [ ]:
try:
    logo = np.load("numpy-logo.npy")
    plt.figsize(figsize=(10,6))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title("Logo")
    plt.grid(False)

    # dark_logo = 1 - logo  inverted the whole color on the wheel

    plt.subplot(122)
    plt.imshow(dark_logo)
    plt.title("Dark_Logo")
    plt.gridd(False)


except FileNotFoundError:
    print("Numpy logo doesnt exist")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4036494265.py, line 9)