In [ ]:
# Main Heading 




In [1]:
print("Hello")

Hello


In [3]:
print("none")
a=10
b=20
print(a+b)

none
30


# Creating an array from list

In [2]:
import numpy as np

## Creating a list from array 

In [4]:
arr_id = np.array([1,2,3,4,5])
print("1D array : " ,arr_id)

arr_2d = np.array([[1,2,3],[3,4,5]])
print("2D array :", arr_2d)

1D array :  [1 2 3 4 5]
2D array : [[1 2 3]
 [3 4 5]]


# list vs Numpy

In [5]:
py_list = [1,23,45]
print(2*py_list)

[1, 23, 45, 1, 23, 45]


In [9]:
py_list = [1,2,3]
print("Here is the list" ,py_list * 2)

Here is the list [1, 2, 3, 1, 2, 3]


In [10]:
np_array = np.array([1,2,3])
print("Python array Multiplication",np_array *2)

Python array Multiplication [2 4 6]


In [19]:
import time 
import numpy as np
start = time.time()
py_list = [i * 2 for i in range(1,100000000)]
print("\n List the operation time ",time.time()-start)

start = time.time()
array_np = np.arange(100000)*2
print("The time required in Numpy array :",time.time()-start)



 List the operation time  4.929515600204468
The time required in Numpy array : 0.00034689903259277344


# Creating array from Scratch

In [ ]:
start = time.time()
zeros = np.zeros((3,4))
print("Zeros Array :\n",time.time()-start)

Zeros Array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
ones = np.ones((2,3))
print("ones matrirces are:", ones)

ones matrirces are: [[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
full = np.full((2,2),3)
print("full:",full)

full: [[3 3]
 [3 3]]


In [26]:
start = time.time()
full = np.full((3,3),0)
print("Zeros Array :\n",time.time()-start)

start = time.time()
zeros = np.zeros((3,4))
print("Zeros Array :\n",time.time()-start)

Zeros Array :
 9.560585021972656e-05
Zeros Array :
 6.389617919921875e-05


In [31]:
random = np.random.random((2,3))
print(random)

sequence = np.arange(0,101,20)
print(sequence)

[[0.5023795  0.54306257 0.84748625]
 [0.4043316  0.64650534 0.18605352]]
[  0  20  40  60  80 100]


# Vector matrix and tensor


In [35]:
vector = np.array([4,5,6])
print("This is vector:",vector)

matrices = np.array([[2,3,4],[7,8,9]])
print("This is called as matrices",matrices)

tensor = np.array([[[2,3,4],[23,34,45]],[[3,4,9],[45,46,46]]])
print("This is tensor:",tensor)

This is vector: [4 5 6]
This is called as matrices [[2 3 4]
 [7 8 9]]
This is tensor: [[[ 2  3  4]
  [23 34 45]]

 [[ 3  4  9]
  [45 46 46]]]


# array Properties

In [38]:
tensor = np.array([[[2,3,4],[23,34,45]],[[3,"String",8.90],[45,46,46]]])
print("shape of the arrray :",tensor.shape)
print("Dimension",tensor.ndim)
print("Size",tensor.size)
print("DType",tensor.dtype)

shape of the arrray : (2, 2, 3)
Dimension 3
Size 12
DType <U32


## Array Reshaping

In [49]:
arr = np.arange(1,13)
print(arr)
reshaped = arr.reshape((2,6))
print(reshaped)

flattend = arr.flatten()
print(flattend)


raveled = arr.ravel() #ravel returns view instead of copy
print(raveled)
print(arr)

transpose = reshaped.T
print(transpose)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
