## Numpy array operations

In [2]:
import numpy as np

In [10]:
import numpy as np
arr = np.array([1,2,3,4])
print("basic slicing:",arr[0:6])
print("With Step:",arr[0:4:2])
print("Negative Indexing:",arr[-4])



basic slicing: [1 2 3 4]
With Step: [1 3]
Negative Indexing: 1


In [14]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print("Specific Element:",arr_2d[1,2])  #this indicates ki 1st row ka second element
print("Specific Element 3:",arr_2d[0,2])

print("Entire Row:",arr_2d[0]) #for Entire row
print("Entire Column:",arr_2d[:,2])

Specific Element: 6
Specific Element 3: 3
Entire Row: [1 2 3]
Entire Column: [3 6 9]


## Sorting


In [28]:

unsorted = np.array([3,1,4,6,2,3,7,8])
print("Sorted Array:",np.sort(unsorted))

arr_2d_Unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d Array:",np.sort(arr_2d_Unsorted,axis=0))

Sorted Array: [1 2 3 3 4 6 7 8]
Sorted 2d Array: [[1 1]
 [2 2]
 [3 3]]


## Filtering

In [43]:
numbers = np.array([1,2,3,4,5,6,6,7,8,10])
even_numbers = numbers[numbers%2 == 0 ]
print("Even Numbers",even_numbers)

Even Numbers [ 2  4  6  6  8 10]


## Filtering with mask

In [34]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])
mask1 = even_numbers < 8
print("Printing it with even_numbers:", even_numbers[mask1])

Numbers greater than 5  [ 6  6  7  8 10]
Printing it with even_numbers: [2 4 6 6]


## Fancing indexing vs np.where()


In [47]:
indices12 = [ 0 , 2 , 9 ]
print(numbers[indices12])

where_result = np.where(numbers > 6)
print(numbers[where_result])

[ 1  3 10]
[ 7  8 10]


In [48]:
conditions_arr = np.where(numbers > 7 , numbers*3 , numbers)
print(conditions_arr)

[ 1  2  3  4  5  6  6  7 24 30]


In [51]:
#understanding where conditions_arr
# if(numbers > 7):
#     numbers*3
# else:
#     numbers

# Adding and Removing DATA

In [58]:
numArr =np.array([1,3,4])
numArr1 =np.array([2,7,5])

combinedArr = np.concatenate((numArr,numArr1))
print(combinedArr)

[1 3 4 2 7 5]


## Array Compatibilty

In [59]:
a = np.array([2,3,4])
b = np.array([7,5,6])
c = np.array([78,9,10])

print("Compatibility Shapes:",a.shape == b.shape)

Compatibility Shapes: True


In [66]:
orgArr = np.array([[1,2,3],[4,5,6],[8,9,10]])
new_row = np.array([[6,7,8]])

row_new_done = np.vstack((orgArr , new_row))
print("Compatibility Shapes:",orgArr.shape == new_row.shape) 
print(row_new_done)

new_col = np.array([[2],[3],[5]])
col_attached_array = np.hstack((orgArr,new_col))
print(col_attached_array)

Compatibility Shapes: False
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [ 6  7  8]]
[[ 1  2  3  2]
 [ 4  5  6  3]
 [ 8  9 10  5]]


# Delete

In [ ]:
arr = np.array([1,2,3,5])

deleted = np.delete(arr,2)
print("Array After Deletion:",deleted)

Array After Deletion: [1 2 5]


: 