### Create a 3*3 NumPy array with values from 0 to 8

In [ ]:
import numpy as np 

array1 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(array1)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


### create a 5*5 identity matrix

In [5]:
array2 = np.eye(5)
print(array2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Create 1D array with 10 elements from 1 to 10 randomly
#### np.random.randint(low,high,size)

In [10]:
array3 = np.random.randint(0,10,10)
print(array3)

[9 6 7 3 8 6 4 8 3 5]


### create 1-D array from 1 to 100 and replace all even numbers with "0"

In [12]:
arr = np.arange(1,101,1)
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [13]:
final = np.where(arr % 2 == 0 , arr==0,arr)
print(final)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23  0
 25  0 27  0 29  0 31  0 33  0 35  0 37  0 39  0 41  0 43  0 45  0 47  0
 49  0 51  0 53  0 55  0 57  0 59  0 61  0 63  0 65  0 67  0 69  0 71  0
 73  0 75  0 77  0 79  0 81  0 83  0 85  0 87  0 89  0 91  0 93  0 95  0
 97  0 99  0]


### Create a 1-D array of 10 numbers and normalize it (vales between 0 and 1)

In [14]:
arr = np.arange(1,11,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
normalized  = (arr - arr.min())/(arr.max() - arr.min())
print(normalized)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### Create 2 arrays and find their dot products

In [19]:
arr1 = np.array([1,2,3])
arr2 =np.array([5,6,7])

print(np.dot(arr1,arr2))

38


### Create a 2-D array and find the row with max sum

In [ ]:
arr3 = np.array([[11,14,5],[6,7,8]])
sum1r = np.sum(arr3 , axis = 1)
print(sum1r)
maxarg = np.argmax(sum1r)

valuemax =arr3[maxarg]
print(valuemax)





[30 21]
[11 14  5]
[9 8 6 4 1]


### Sort an array in descending order

In [37]:
array5  =  np.array([1,4,6,8,9])
print(np.sort(array5)[::-1])

[9 8 6 4 1]


### Reshape an 1-D array of 16 elements in a 4*4 matrix

In [41]:
array79 = np.arange(1,17,1)
print(array79)
reshaping79 = array79.reshape((4,4))
print(reshaping79)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Use np.where to replace all values less than zero with -1 and greater than 0 with +1/1

In [43]:
arr90 = np.array([56,-4,23,-68,78,56,-2])
fixed = np.where(arr90 > 0 , 1 ,-1)
print(fixed)

[ 1 -1  1 -1  1  1 -1]
